name: install

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  install:
    if: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ 2.3.8, 2.4.9, 2.5.7, 2.6.5, 2.7.0, jruby-9.2.11.0 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: Install rubygems
        run: ruby -Ilib -S rake install
    timeout-minutes: 10
