name: jruby-bundler

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  jruby_bundler:
    if: false

    runs-on: ubuntu-latest

    env:
      RGV: ..

    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: jruby-9.2.11.0
          bundler: none
      - name: Prepare dependencies
        run: |
          bin/rake spec:parallel_deps
        working-directory: ./bundler
      - name: Run Test
        run: |
          bin/parallel_rspec spec --test-options '--tag jruby'
        working-directory: ./bundler
      - name: Install local bundler
        run: |
          bin/rake install:local
        working-directory: ./bundler
      - name: Run a warbler project
        run: |
          cd spec/realworld/fixtures/warbler
          bundle install
          bundle exec warble
          java -jar warbler.jar
        working-directory: ./bundler
