name: macos

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  macos:
    if: false
    runs-on: macos-latest
    strategy:
      matrix:
        ruby: [ 2.4.9, 2.5.7, 2.6.5, 2.7.0 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: Install Dependencies
        run: rake setup
      - name: Run Test
        run: rake test
    timeout-minutes: 15
