name: ubuntu

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ 2.3.8, 2.4.9, 2.5.7, 2.6.5, 2.7.0, jruby-9.2.11.0 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: Run Test
        run: |
          rake setup
          rake test
    timeout-minutes: 60
